sudo: false
dist: trusty
language: elixir
elixir:
  - '1.3.4'
node_js:
  - '6'
otp_release:
  - '18.1'
cache:
  directories:
    - node_modules
    - deps
addons:
  postgresql: '9.4'
services:
  - postgresql
before_install:
  - mix local.hex --force
install:
  - mix deps.get
  - npm install -g yarn
  - yarn install
before_script:
  - cp config/travis.exs config/test.exs
  - mix ecto.create
#  - mix ecto.migrate
script:
  - mix test --exclude integration
env:
  global:
    - MIX_ENV=test