sudo: required
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 18.1
cache:
  directories:
    - node_modules
    - deps
addons:
  postgresql: '9.4'
services:
  - postgresql
before_install:
  - sudo apt-get install -y build-essential curl
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
install:
  - npm install -g yarn
  - yarn install
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test --exclude integration